---
title: "Bac Kan vaccine registry"
number-sections: true
format:
  html:
    toc: true
    toc-depth: 4
editor: source
editor_options: 
  chunk_output_type: console
#bibliography: references.bib
#csl: the-american-naturalist.csl
---

```{r include = FALSE, eval = FALSE}
knitr::purl("index.qmd", "tmp.R", documentation = FALSE)
source("tmp.R")
file.remove("tmp.R")

add_nojekyll <- function() {
  file <- ".nojekyll"
  file.create(file)
  gert::git_add(file)
  gert::git_commit("Adding the .nojekyll file")
  gert::git_push()
  rm(file)
}
```

```{r include = FALSE}
par2 <- function(...) par(..., mgp = c(1.5, .5, 0), bty = "n")

knitr::knit_hooks$set(
  margin1 = function(before, options, envir) {
    if (before) par2(plt = c(.105, .97, .15, .95)) else NULL
  })

eps <- .8
knitr::opts_chunk$set(margin1    = TRUE,
                      fig.retina = 2,
                      fig.align  = "center",
                      fig.height = eps * 5, # default is 5
                      fig.width  = eps * 7) # default is 7 and maximum possible is 8.3
```

## Constants

The folder that contains the data files:

```{r}
OneDrive <- paste0("/Users/", Sys.getenv("USER"), "/Library/CloudStorage/",
                    "OneDrive-OxfordUniversityClinicalResearchUnit/")

path2data <- paste0(OneDrive, "data/vaccine registry Bac Kan/")
```

```{r include = FALSE}
path2cache <- paste0(OneDrive, "GitHub/choisy/vaccine registry/cache/")
if (! dir.exists(path2cache)) dir.create(path2cache)
make_path <- function(x) paste0(path2cache, x)
file_exists <- function(x) file.exists(make_path(x))
readRDScache <- function(x) readRDS(make_path(x))
saveRDScache <- function(object, file) saveRDS(object, make_path(file))
```

## Packages

```{r}
library(tibble)
```

## Functions

```{r}
size <- function(x) print(object.size(x), units = "auto")
```

```{r}
readRDS2 <- function(x) as_tibble(readRDS(paste0(path2data, x)))
```


## Loading the data

```{r}
vacrecords <- readRDS2("backan_vacrecords.rds")
pids <- readRDS2("backan_pids.rds")
```

```{r}
dim(vacrecords)
dim(pids)
```

```{r}
size(vacrecords)
size(pids)
```

